---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
raw_data = read.csv('CAPOP.csv')
capop.ts = ts(raw_data$CAPOP, start = c(1900, 1), end = c(2021, 1))
plot(capop.ts, ylab = "Population (in thousands)", xlab = "Time (in years)", main = "CA Population")
```

```{r}
t = 1: length(capop.ts)
lin.model = lm(capop.ts ~ 1 + t)
plot(t, capop.ts, type = "l", xlab = "Time", ylab = "CA Population", main = "Population of California")
points(t, lin.model$fitted, type = "l", col = "red")
summary(lin.model)

stderrs = c(395.791, 5.585)
bhat = lin.model$coefficients
n = length(capop.ts)
```

```{r}
#posterior density for intercept parameter:
j = 1
vals = c(bhat[j] - stderrs[j]*seq(5, 0, length = 100), bhat[j], bhat[j] + stderrs[j]*seq(0, 5, length = 100))
plot(vals, (1/stderrs[j])*(dt((vals - bhat[j])/(stderrs[j]), df = n-2)), type = "l", xlab = "x", ylab = "density values", main = "Standard t-density")
abline(v = bhat[j])
points(vals, dnorm(vals, mean = bhat[j], sd = stderrs[j]), col = "red", type = "l")
```

```{r}
#posterior density for slope parameter:
j = 2
vals = c(bhat[j] - stderrs[j]*seq(5, 0, length = 100), bhat[j], bhat[j] + stderrs[j]*seq(0, 5, length = 100))
plot(vals, (1/stderrs[j])*(dt((vals - bhat[j])/(stderrs[j]), df = n-2)), type = "l", xlab = "x", ylab = "density values", main = "Standard t-density")
abline(v = bhat[j])
points(vals, dnorm(vals, mean = bhat[j], sd = stderrs[j]), col = "red", type = "l")
```

```{r}
df <- n-2
#Estimate of sigma:
sighat = sqrt((sum((lin.model$residuals)^2))/(n-2)) #this is also denoted by the Residual Standard Error
X = model.matrix(lin.model)
Sigma.mat = (sighat^2)*solve(t(X) %*% X)
Sigma.mat
```

```{r}
N = 30
library(mvtnorm)
post.samples = (rbind(bhat)[rep(1, N), ]) + (rmvnorm(N, sigma = Sigma.mat))/(sqrt((rchisq(N, df = n-2))/(n-2)))

plot(t, capop.ts, type = "l", xlab = "Time", ylab = "CA Population", main = "Population of California")

for(k in 1:N) {
   abline(a = post.samples[k, 1], b = post.samples[k, 2], col = "blue")
}
```

```{r}
# Prediction of population in 2025
X_inverse <- matrix(solve(t(X) %*%X), ncol = 2)
a <- c(1, 126)
sigma_predict <- sighat * sqrt(1 + (c(t(a)) %*% X_inverse) %*% a)
sigma_predict
```
