---
title: "R Notebook"
output: html_notebook
---
```{r}
uspop.raw = read.csv("POPTHM.csv")
dt = uspop.raw$POPTHM

plot(uspop.raw$POPTHM, type = "l", xlab = 'time', ylab = 'Population')
n <- length(dt)
time <- 1:n
```
```{r}
p = 2
n = length(dt)
yt = dt[(p+1):n]
Xmat = matrix(1, (n-p), 1)

for(j in 1:p)
{
   Xmat = cbind(Xmat, dt[(p-j+1):(n-j)])
}

model = lm(yt ~ -1 + Xmat)
summary(model)
```
```{r}
X <- Xmat
sigma_hat <- sqrt((sum((model$residuals)^2))/(n-2*p-1))
solve(t(X) %*% X) * (sigma_hat^2)
```
```{r}
#define population mean and standard deviation
population_mean <- -0.95182    
population_sd <- 0.0001292716^0.5
alpha <- 0.05
object <- 'phi_2'

#define upper and lower bound
lower_bound <- population_mean - population_sd
upper_bound <- population_mean + population_sd

#Create a sequence of 1000 x values based on population mean and standard deviation
x <- seq(-4, 4, length = 1000) * population_sd + population_mean

#create a vector of values that shows the height of the probability distribution
#for each value in x
y <- dnorm(x, population_mean, population_sd)

#plot normal distribution with customized x-axis labels
plot(x,y, type = "l", lwd = 2, axes = FALSE, xlab = object, ylab = 'Probability density', main = 'Distribution of phi_2')

# Use quantile function to compute the confidence interval (CI)
lo <- qnorm(alpha/2,   mean=population_mean, sd=population_sd)  # lower CI bound
hi <- qnorm(1-alpha/2, mean=population_mean, sd=population_sd)  # upper CI bound

sd_axis_bounds = 5
axis_bounds <- seq(-sd_axis_bounds * population_sd + population_mean,
                    sd_axis_bounds * population_sd + population_mean,
                    by = population_sd)
axis(side = 1, at = axis_bounds, pos = 0)

xci <- seq(lo, hi, len=100)             # background: confidence interval
yci <- dnorm(xci, mean=population_mean, sd=population_sd)
xx <- c(xci, rev(xci))
yy <- c(0*yci, rev(yci))
polygon(xx,yy,col=gray(0.9), border=NA)

# mean
lines(c(population_mean,population_mean), c(0,dnorm(population_mean,mean=population_mean,sd=population_sd)), lty="dashed", lwd=0.5) 
print(lo)
print(hi)
```
```{r}
samples <- data.frame(X=rchisq(1:100000, df=n - 2*p - 1))
S_beta_hat <- sqrt((sum((model$residuals)^2)))
sigma_samples <- sqrt(S_beta_hat / samples)
hist(unlist(sigma_samples), breaks = 100, main = 'histogram of sigma', xlab='sigma')
quantile(unlist(sigma_samples), probs=c(0.025,0.975))
```
```{r}
(S_beta_hat/(n - 2*p - 1))^0.5

```
```{r}
dt[761]
dt[762]
```
```{r}
#Predictions with the AR(p) model:
k = 36 #k predictions into the future
p = 2
yhat = c(dt[1:n], rep(-9999, k))
for(i in 1:k)
{
    ans = model$coefficients[1]
    for(j in 1:p)
    {
       ans = ans + (model$coefficients[(j+1)])*yhat[n+i-j]
    }
    yhat[(n+i)] = ans
}
predvalues = yhat[-(1:n)]
predvalues
```
```{r}
plot(time, dt, main='Prediction', ylab='US Population', type= 'l')
time_predict <- 763:(763+35)
points(time_predict, predvalues, type = "l", col = "red")
abline(v=762, lty=2)
```
```{r}
resdf = n - 2*p - 1
sighat = sqrt((sum((model$residuals)^2))/resdf) #this is also denoted by the Residual Standard Error
Gamhat = matrix(sighat^2, 1, 1) #this is the uncertainty for the first i.e., (n+1)^th prediction
#The following vector vkp is the vector a from the lecture notes
vkp = matrix(model$coefficients[2], 1, 1) #this is the estimate for phi1
for(i in 1:(k-1))
{
    covterm = Gamhat %*% vkp
    varterm = (sighat^2) + (t(vkp) %*% (Gamhat %*% vkp))
    Gamhat = cbind(Gamhat, covterm)
    Gamhat = rbind(Gamhat, c(t(covterm), varterm))
    if (i < p) {vkp = c(model$coefficients[(i+2)], vkp)}
    if (i >= p) {vkp = c(0, vkp)}
}
Gamhat
predsd = sqrt(diag(Gamhat))
#Plotting predictions with uncertainty bands (+/- 2 standard deviation bounds):
predlower = predvalues - 2*predsd
predupper = predvalues + 2*predsd

yhatlower = c(dt, predlower)
yhatupper = c(dt, predupper)

plot(c((1:(n+k)), (1:(n+k)), (1:(n+k))), c(yhat, yhatlower, yhatupper), type = "n", xlab = "Time", ylab = "Data", main = 'Prediction wiht uncertainty')
points((1:(n+k)), yhat, type = "l")
points(1:n, dt, type = "l")
points((n+1):(n+k), predvalues, type = "l", col = "blue")
points((n+1):(n+k), predlower, type = "l", col = "red")
points((n+1):(n+k), predupper, type = "l", col = "red")
abline(v = n+1)
```

```{r}
predsd
```
```{r}
p = 2
n = length(dt)
yt = dt[1:(n-p)]
Xmat = matrix(1, (n-p), 1)

for(j in 1:p)
{
   Xmat = cbind(Xmat, dt[(1+j):(n+j-2)])
}

model = lm(yt ~ -1 + Xmat)
summary(model)
```
```{r}
S_beta_hat <- sqrt((sum((model$residuals)^2)))
(S_beta_hat/(n - 2*p - 1))^0.5
```
```{r}
#Predictions with the AR(p) model:
k = 36 #k predictions into the future
p = 2
yhat = c(rep(-9999, k), dt[1:n])
for(i in 1:k)
{
    ans = model$coefficients[1] # phi_0
    for(j in 1:p)
    {
       ans = ans + (model$coefficients[(j+1)])*yhat[(37-i)+j]
    }
    yhat[37-i] = ans
}
predvalues = yhat[1:36]
predvalues
```
```{r}
plot(37:(762+37-1), dt, main='Prediction', ylab='US Population', type= 'l', xlab = 'time')
time_predict <- 1:36
points(time_predict, predvalues, type = "l", col = "red")
abline(v=36, lty=2)
```


```{r}
resdf = n - 2*p - 1
sighat = sqrt((sum((model$residuals)^2))/resdf) #this is also denoted by the Residual Standard Error
Gamhat = matrix(sighat^2, 1, 1) #this is the uncertainty for the first i.e., (n+1)^th prediction
#The following vector vkp is the vector a from the lecture notes
vkp = matrix(model$coefficients[2], 1, 1) #this is the estimate for phi1
for(i in 1:(k-1))
{
    covterm = Gamhat %*% vkp
    varterm = (sighat^2) + (t(vkp) %*% (Gamhat %*% vkp))
    Gamhat = cbind(Gamhat, covterm)
    Gamhat = rbind(Gamhat, c(t(covterm), varterm))
    if (i < p) {vkp = c(model$coefficients[(i+2)], vkp)}
    if (i >= p) {vkp = c(0, vkp)}
}
Gamhat
predsd = sqrt(diag(Gamhat))
predsd <- predsd[36:1]
#Plotting predictions with uncertainty bands (+/- 2 standard deviation bounds):
predlower = predvalues - 2*predsd
predupper = predvalues + 2*predsd

yhatlower = c(dt, predlower)
yhatupper = c(dt, predupper)

```

```{r}
plot(c((1:(n+k)), (1:(n+k)), (1:(n+k))), c(yhat, yhatlower, yhatupper), type = "n", xlab = "Time", ylab = "Data", main = 'Prediction wiht uncertainty')
points((1:(n+k)), yhat, type = "l")
points(37:(762+37-1), dt, type = "l")
points(1:36, predvalues, type = "l", col = "blue")
points(1:36, predlower, type = "l", col = "red")
points(1:36, predupper, type = "l", col = "red")
abline(v = 36)
```

